version: "3"

services:
  db:
    image: postgres:14.0-alpine
    environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  media:
  static:
  postgres-data:
