# Generated by Django 4.1.7 on 2023-03-29 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_notes_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='url',
            field=models.SlugField(default=datetime.datetime(2023, 3, 29, 9, 19, 57, 900786, tzinfo=datetime.timezone.utc), max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
