# Generated by Django 4.1.7 on 2023-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_notes_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='url',
            field=models.SlugField(blank=True, error_messages={'unique': 'This url has already been registered! Choose something other.'}, max_length=300, unique=True),
        ),
    ]
